language:
  #- android
  - objective-c

os:
  # The value of the $TRAVIS_OS_NAME variable is set to linux or osx according to the operating system a particular build is running on
  # Usage: - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  # - linux
  - osx

osx_image: xcode8.2


env:
  global:
    - EMULATOR_API_LEVEL=24

# jdk:
#   - oraclejdk8

sudo: false

android:
  components:
    # Uncomment the lines below if you want to use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.3

    # The SDK version used to compile your project
    - android-24

    # Needed by emulator
    - android-$EMULATOR_API_LEVEL

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image, if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

    # To get a list of available exact component names and descriptions run the command android list sdk --no-ui --all --extended

before_install:
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - nvm install 6
  - node --version
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -version; fi

install:
  - npm install
  - npm install -g cordova
  - cordova --version

before_script:
  - pwd
  - echo $PATH
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi armeabi-v7a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then emulator -avd test -no-audio -no-window -memory 1024 & fi
  #- which adb
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then android-wait-for-emulator; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then adb shell input keyevent 82 & fi #KEYCODE_MENU
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then adb shell mount -o rw,remount rootfs /; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run copy-test-images:android:emulator; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat ./node_modules/adb-ci/adb-ci.txt; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run test:android; fi
  - if [[ "$TRAVIS_OS_NAME" == "ios" ]]; then npm run test:ios; fi

after_failure:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat ./node_modules/adb-ci/adb-ci.txt; fi
